version: 2
jobs:
  test:
    docker:
    - image: php:8.0.0RC2-zts-buster
    steps:
    #- run: sudo rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - checkout
    - run: composer validate --strict
    - run: composer install --no-interaction --no-suggest
    - run: composer test:syntax -- --no-progress
    - run: composer test:cs
    - run: composer test:phpstan -- --memory-limit=1G --no-progress
workflows:
  version: 2
  workflow:
    jobs:
    - test:
        filters:
          branches:
            only:
            - master
            - php8
